# Generated by Django 5.1.3 on 2024-11-23 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_food_discount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="food",
            old_name="discount",
            new_name="discount_percent",
        ),
    ]
