# Generated by Django 5.1.3 on 2024-11-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_rename_discount_food_discount_percent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
